---

- name: Assert dawarich_version is supported
  ansible.builtin.assert:
    that: >-
      dawarich_version in ['latest', 'prod', 'rc'] or
      dawarich_version | split('-') | first is version(min_dawarich_version, '>=', version_type='semver')
    success_msg: Dawarich version '{{ dawarich_version }}' supported.
    fail_msg: >-
      Dawarich version '{{ dawarich_version }}' is not supported by the current version of this role.
      Version must be >= {{ min_dawarich_version }} or a named/text tag (e.g. latest).
      If you think this failure is a false negative, please open an issue on GitHub:
      https://github.com/tigattack/ansible-role-dawarich
  vars:
    min_dawarich_version: "{{ lookup('ansible.builtin.file', 'min_dawarich_version.txt') }}"

- name: Assert dawarich_photon_version is supported
  ansible.builtin.assert:
    that: >-
      dawarich_photon_version == 'latest' or
      dawarich_photon_version is version(min_photon_version, '>=', version_type='semver')
    success_msg: Photon version '{{ dawarich_photon_version }}' supported.
    fail_msg: >-
      Photon version '{{ dawarich_photon_version }}' is not supported.
      Version must be >= '{{ min_photon_version }}' or a named/text tag (e.g. latest).
      If you think this failure is a false negative, please open an issue on GitHub:
      https://github.com/tigattack/ansible-role-dawarich
  when: dawarich_deploy_photon
  vars:
    min_photon_version: '1.0.0'

- name: Assert dawarich_workers_count is at least 1
  ansible.builtin.assert:
    that: dawarich_workers_count >= 1
    fail_msg: dawarich_workers_count must be at least 1

- name: Assert PostgreSQL variables are not defined
  ansible.builtin.assert:
    that: query('varnames', 'dawarich_postgres', 'dawarich_deploy_postgres') | length == 0
    fail_msg: >-
      PostgreSQL is no longer supported due to breaking changes in Dawarich.
      Please see the updated information in the tigattack.dawarich role documentation.

- name: Ensure DB major update isn't pending
  when: dawarich_postgis_host == 'dawarich-db'
  block:
    - name: Get dawarich-db container info
      community.docker.docker_container_info:
        name: dawarich-db
      register: dawarich_postgis_container_info

    - name: Compare versions if container found
      when:
        - dawarich_postgis_container_info.container is defined
        - dawarich_postgis_container_info.container not in [None, {}]
      block:
        - name: Parse current and target DB major versions
          ansible.builtin.set_fact:
            db_major_version_target: >-
              {{ dawarich_postgis_version | regex_search('^(\d+)', '\1') | first | int }}
            db_major_version_current: >-
              {{ dawarich_postgis_container_info.container.Config.Image | regex_search('^\w+/postgis:(\d+)', '\1') | first | int }}

        - name: Determine if DB major update is pending
          ansible.builtin.set_fact:
            db_major_update_pending: >-
              {{ db_major_version_target != db_major_version_current }}

        - name: Confirm DB major update
          ansible.builtin.pause:
            prompt: >-
              IMPORTANT: A major update to the database is pending.
              Please follow the instructions in the Dawarich documentation before proceeding:
              https://dawarich.app/docs/tutorials/update-postgresql/
              Press enter to continue, Ctrl+C to interrupt
          when: db_major_update_pending

- name: Detect usage of removed variables
  ansible.builtin.set_fact:
    removed_vars_used: >-
      {{ removed_vars_used | default([]) + [item] if (lookup('vars', item, default='varnotfound') != 'varnotfound') else removed_vars_used | default([]) }}
  loop:
    - dawarich_enable_telemetry
    - dawarich_distance_unit
    - dawarich_queue_db_host
    - dawarich_queue_db_name
    - dawarich_queue_db_username
    - dawarich_queue_db_password
    - dawarich_redis_db_number
    - dawarich_photon_country_code

- name: Warn if using removed variables
  ansible.builtin.pause:
    prompt: >-
      IMPORTANT: The following variable(s) have been set, but have been removed due to recent changes:
      {{ removed_vars_used | join(', ') }}.
      Please confirm that you have read the warning above and that you are aware of the changes.
      If you are unsure, please refer to the documentation or open an issue on GitHub.
      Press enter to continue, Ctrl+C to interrupt
  when: removed_vars_used is defined and removed_vars_used | length > 0
