---

- name: Get Dawarich containers
  community.docker.docker_host_info:
    containers: true
    containers_all: true
    containers_filters:
      label:
        - deployment_name=dawarich
  register: dawarich_containers

- name: Identify Dawarich workers
  ansible.builtin.set_fact:
    existing_workers: >-
      {{ dawarich_containers.containers | selectattr('Names', 'search', 'dawarich-sidekiq') |
      map(attribute='Names') | map('first') | map('replace', '/', '') | list | sort }}

- name: Cleanup Sidekiq containers
  when: existing_workers | length > 0
  block:
    - name: Remove Sidekiq container(s)
      community.docker.docker_container:
        name: "{{ item }}"
        state: absent
      loop: "{{ existing_workers }}"

- name: Cleanup unused gem_cache directory
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    - "{{ [dawarich_data_path, 'gem_cache_app'] | path_join }}"
    - "{{ [dawarich_data_path, 'gem_cache_sidekiq'] | path_join }}"
  diff: false # Hide huge output

- name: Remove Redis container
  community.docker.docker_container:
    name: "{{ dawarich_redis_host | default('dawarich-redis') }}"
    state: absent

- name: Remove Redis data directory
  ansible.builtin.file:
    path: "{{ [dawarich_data_path, 'redis'] | path_join }}"
    state: absent

- name: Remove old queue SQLite database
  block:
    - name: Find old queue SQLite database files
      ansible.builtin.find:
        paths: "{{ [dawarich_data_path, 'worker_db'] | path_join }}"
        patterns: "dawarich_queue.sqlite*"
      register: old_queue_sqlite_files

    - name: Remove old queue SQLite database files
      ansible.builtin.file:
        path: "{{ item.path }}"
        state: absent
      loop_control:
        label: "{{ item.path | basename }}"
      when: old_queue_sqlite_files.matched > 0
      loop: "{{ old_queue_sqlite_files.files }}"
