---

- name: Create Dawarich Docker network
  community.docker.docker_network:
    name: "{{ dawarich_docker_network_name }}"
    state: present

- name: Deploy Dawarich containers and await healthy state # noqa args[module]
  community.docker.docker_container: "{{ item }}"
  loop: "{{ dawarich_containers | from_yaml }}"
  loop_control:
    label: "{{ item.name }}"
  notify: Prune Docker images

- name: Include deploy_photon.yml
  ansible.builtin.include_tasks:
    file: deploy_photon.yml
  when: dawarich_deploy_photon

- name: Include cleanup_workers.yml
  ansible.builtin.include_tasks:
    file: cleanup_workers.yml
