---

# Pre-deployment checks, migrations, etc. for Dawarich deployment

- name: Include assertions.yml
  ansible.builtin.include_tasks:
    file: assertions.yml

- name: Cleanup Dawarich queue database if it exists
  when:
    - dawarich_deploy_postgis
    # Ensure we don't accidentally drop the main database:
    - dawarich_queue_db_name | default('dawarich_queue') != dawarich_postgis_db_name
  block:
    - name: Check if Dawarich PostGIS container exists
      community.docker.docker_container_info:
        name: "{{ dawarich_postgis_container.name }}"
      register: check_pg_container_exists

    - name: Check if dawarich_queue DB exists
      community.docker.docker_container_exec:
        container: "{{ dawarich_postgis_container.name }}"
        command: bash -c "psql -U {{ dawarich_postgis_username }} -lqt | grep -q {{ dawarich_queue_db_name | default('dawarich_queue') }}"
      when: check_pg_container_exists.exists
      changed_when: false
      register: queue_db_exists
      failed_when:
        - queue_db_exists.rc not in [0, 1]
        - >-
          queue_db_exists.stderr is defined and queue_db_exists.stderr != "" or
          queue_db_exists.stdout is defined and queue_db_exists.stdout != ""

    - name: Stop Dawarich & drop queue DB
      when:
        - check_pg_container_exists.exists
        - queue_db_exists.rc == 0
      block:
        - name: Stop Dawarich
          community.docker.docker_container:
            name: "{{ dawarich_app_container.name }}"
            state: stopped

        - name: Drop dawarich_queue DB if it exists
          community.docker.docker_container_exec:
            name: "{{ dawarich_postgis_container.name }}"
            command: psql -U {{ dawarich_postgis_username }} -c "DROP DATABASE {{ dawarich_queue_db_name | default('dawarich_queue') }}"
