---

# Pre-deployment checks, migrations, etc. for Dawarich deployment

- name: Include assertions.yml
  ansible.builtin.include_tasks:
    file: assertions.yml

- name: Cleanup Dawarich queue database if it exists
  when:
    - dawarich_deploy_postgis
    # Ensure we don't accidentally drop the main database:
    - dawarich_queue_db_name | default('dawarich_queue') != dawarich_postgis_db_name
  block:
    - name: Check if dawarich_queue DB exists
      community.docker.docker_container_exec:
        container: "{{ dawarich_postgis_container.name }}"
        command: >-
          psql -U {{ dawarich_postgis_username }} -lqt |
          grep -q {{ dawarich_queue_db_name | default('dawarich_queue') }}
      register: queue_db_exists

    - name: Stop Dawarich & drop queue DB
      when: queue_db_exists.rc == 0
      block:
        - name: Stop Dawarich
          community.docker.docker_container:
            name: "{{ dawarich_app_container.name }}"
            state: stopped

        - name: Drop dawarich_queue DB if it exists
          community.docker.docker_container_exec:
            name: "{{ dawarich_postgis_container.name }}"
            command: >-
              psql -U {{ dawarich_postgis_username }} -c "DROP DATABASE {{ dawarich_queue_db_name | default('dawarich_queue') }}"
