---
- name: Converge
  hosts: all
  pre_tasks:
    - name: Dawarich version notice
      ansible.builtin.debug:
        msg: "Testing with Dawarich version '{{ dawarich_version }}'"

  roles:
    - role: ansible-role-dawarich
      vars:
        dawarich_postgis_password: _!CHANGEME!_
        dawarich_encryption_secret_key: 1234567890
