---
dependency:
  name: galaxy
  options:
    role-file: molecule/resources/requirements.yml
    requirements-file: requirements.yml

driver:
  name: docker

platforms:
  - name: instance
    image: "geerlingguy/docker-${MOLECULE_DISTRO:-debian13}-ansible:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
    pre_build_image: true

provisioner:
  name: ansible
  config_options:
    defaults:
      inject_facts_as_vars: false
  playbooks:
    prepare: ../resources/prepare.yml
    converge: ../resources/converge.yml
  inventory:
    group_vars:
      all:
        dawarich_version: ${DAWARICH_TEST_VERSION:-latest}
        dawarich_deploy_photon: true
        dawarich_photon_api_use_https: false
        dawarich_photon_region: 'andorra'
        dawarich_photon_extra_env:
          LOG_LEVEL: DEBUG
