---
dependency:
  name: galaxy
  options:
    role-file: molecule/resources/requirements.yml
    requirements-file: requirements.yml

driver:
  name: docker

platforms:
  - name: instance
    image: "geerlingguy/docker-${MOLECULE_DISTRO:-debian13}-ansible:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
      # Mount Docker storage to a volume to enable overlay2 driver
      # Without this, Docker falls back to VFS which uses a lot more space
      - /var/lib/docker
    cgroupns_mode: host
    privileged: true
    pre_build_image: true

ansible:
  playbooks:
    prepare: ../resources/prepare.yml
    converge: ../resources/converge.yml
  cfg:
    defaults:
      callbacks_enabled: profile_tasks
      inject_facts_as_vars: false

provisioner:
  name: ansible
  inventory:
    group_vars:
      all:
        dawarich_version: ${DAWARICH_TEST_VERSION:-latest}
        dawarich_deploy_photon: true
        dawarich_photon_api_use_https: false
        dawarich_photon_region: 'andorra'
        dawarich_photon_extra_env:
          LOG_LEVEL: DEBUG

scenario:
  test_sequence:
    - dependency
    - create
    - prepare
    - converge
    - idempotence
    - verify
    - destroy
