---
- name: Verify
  hosts: all
  pre_tasks:
    - name: Get dawarich-photon container info
      community.docker.docker_container_info:
        name: dawarich-photon
      register: container_info

    - name: Parse dawarich-photon container IP
      ansible.builtin.set_fact:
        photon_container_ip: "{{ container_info.container.NetworkSettings.Networks.values() | map(attribute='IPAddress') | list | first }}"

  tasks:
    - name: Assert dawarich-photon is healthy
      ansible.builtin.assert:
        that: container_info.container.State.Health.Status == 'healthy'
        success_msg: Photon container passed health check.
      register: _result
      until: _result is not failed
      retries: 60 # 60 * 5 seconds = 5min
      delay: 5
      ignore_errors: true

    - name: Assert dawarich-photon API responds
      ansible.builtin.uri:
        url: "http://{{ photon_container_ip }}:2322/api/?q=Speedwell+Island"
        status_code: 200

    - name: Handle healthcheck failure
      when: _result is failed
      block:
        - name: Get dawarich-photon container logs
          ansible.builtin.command:
            cmd: "docker logs dawarich-photon"
          register: logs
          changed_when: false

        - name: Dump logs
          ansible.builtin.debug:
            msg: "{{ logs.stdout }}"

        - name: Dump dawarich-photon container healthcheck info
          ansible.builtin.debug:
            msg: "{{ container_info.container.State.Health }}"

        - name: Fail
          ansible.builtin.fail:
            msg: Photon container did not reach a healthy state before timeout.
