---
- name: Verify
  hosts: all
  pre_tasks:
    - name: Get dawarich-server container info
      community.docker.docker_container_info:
        name: dawarich-server
      register: container_info

  tasks:
    - name: Assert dawarich-server is healthy
      ansible.builtin.assert:
        that: container_info.container.State.Health.Status == 'healthy'
        success_msg: Dawarich container passed health check.

    - name: Ensure dawarich-server is configured for Prometheus
      ansible.builtin.assert:
        that:
          - "'PROMETHEUS_EXPORTER_ENABLED=true' in container_info.container.Config.Env"
          - "'SIDEKIQ_METRICS_URL=http://dawarich-sidekiq-1:9394/metrics' in container_info.container.Config.Env"
