---
- name: Verify
  hosts: all
  pre_tasks:
    - name: Get dawarich-sidekiq-1 container info
      community.docker.docker_container_info:
        name: dawarich-sidekiq-1
      register: worker_info_1

    - name: Get dawarich-sidekiq-2 container info
      community.docker.docker_container_info:
        name: dawarich-sidekiq-2
      register: worker_info_2

  tasks:
    - name: Assert expected count of Dawarich workers
      ansible.builtin.assert:
        that: worker_info_1.exists and worker_info_2.exists
        success_msg: Found expected number of Dawarich workers (2).

    - name: Assert Dawarich workers are healthy
      ansible.builtin.assert:
        that: item == 'healthy'
        success_msg: Dawarich worker {{ ansible_loop.index }} passed health check.
      loop:
        - "{{ worker_info_1.container.State.Health.Status }}"
        - "{{ worker_info_2.container.State.Health.Status }}"
      loop_control:
        extended: true
