---
name: Test
on:
  push:
    branches: '*'
    tags-ignore:
      - '**'
  schedule:
    - cron: "0 5 * * 1"
  workflow_dispatch:
  workflow_call:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ansible/ansible-lint@v25.4.0
        with:
          requirements_file: requirements.yml
          args: "--exclude molecule"

  gather_tests:
    runs-on: ubuntu-latest
    outputs:
      tests: ${{ steps.tests.outputs.tests }}
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: |
            molecule

      - name: Get Molecule tests
        id: tests
        # with_photon test is disabled for now as as it runs out of space on the runner somehow.
        run: |
          tests=$(
            find molecule -type d -maxdepth 1 -mindepth 1 -not -name 'resources' -not -name 'with_photon' | \
            sed 's/molecule\///' | \
            sort | \
            jq -R -s -c 'split("\n") | map(select(length > 0))'
          )
          echo "$tests"
          echo "tests=$tests" >> $GITHUB_OUTPUT

  molecule_test:
    runs-on: ubuntu-latest
    needs: [gather_tests]
    strategy:
      fail-fast: false
      matrix:
        test: ${{ fromJSON(needs.gather_tests.outputs.tests) }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/cache@v4
        with:
          path: |
            ~/.ansible/roles
            ~/.ansible/collections
          key: ${{ runner.os }}-ansible-deps-${{ hashFiles('requirements.yml', 'molecule/resources/requirements.yml') }}

      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
          cache: 'pip'

      - run: pip install -r requirements.txt

      - run: |
          dawarich_version=$(cat min_dawarich_version.txt)
          echo "DAWARICH_TEST_VERSION=${dawarich_version}" >> $GITHUB_ENV

      - run: molecule -v test -s ${{ matrix.test }}
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
